version: '2'
services:
  carritodecompras-app:
    image: carritodecompras
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://carritodecompras-mariadb:3306/carritodecompras?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  carritodecompras-mariadb:
    extends:
      file: mariadb.yml
      service: carritodecompras-mariadb
